# Form implementation generated from reading ui file 'c:\Users\Mateus C\Desktop\PyGuiRDP\LogIn.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(333, 479)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Mateus C\\Desktop\\PyGuiRDP\\log-in.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.UserIcon = QtWidgets.QLabel(parent=self.centralwidget)
        self.UserIcon.setGeometry(QtCore.QRect(110, 20, 101, 101))
        self.UserIcon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.UserIcon.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.UserIcon.setText("")
        self.UserIcon.setPixmap(QtGui.QPixmap("c:\\Users\\Mateus C\\Desktop\\PyGuiRDP\\log-in.png"))
        self.UserIcon.setScaledContents(True)
        self.UserIcon.setObjectName("UserIcon")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 150, 291, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.User = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.User.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase)
        self.User.setText("")
        self.User.setObjectName("User")
        self.verticalLayout_2.addWidget(self.User)
        self.Password = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Password.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.Password.setInputMask("")
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password.setObjectName("Password")
        self.verticalLayout_2.addWidget(self.Password)
        self.Entrar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.Entrar.setFlat(False)
        self.Entrar.setObjectName("Entrar")
        self.verticalLayout_2.addWidget(self.Entrar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Acessar Servidor"))
        self.User.setPlaceholderText(_translate("MainWindow", "Usuário"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.Entrar.setText(_translate("MainWindow", "Entrar"))
